spring:
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
  datasource:
    url: jdbc:hsqldb:file:c:/db/mysqlbackup/db;shutdown=true
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    validation-query: select 1 from INFORMATION_SCHEMA.SYSTEM_USERS
    test-on-borrow: true
  jooq:
    sql-dialect: HSQLDB
  quartz:
    job-store-type: memory # jdbc, memory
    jdbc:
      initialize-schema: never # always, embeded.
  flyway:
    baseline-version: 1_1
  mail:
    host: smtp.qq.com
    port: 587 #465
    username: 
    password: 
    protocol: smtp
    properties:
      mail.smtp.auth: true
      #mail.smtp.starttls.enable: true
  messages:
    use-code-as-default-message: false
    basename: messages.command_msg
logging:
  file: log/spring.log
  file.max-size: 5MB
  file.max-history: 100
#  quartz
#    jdbc
#      initialize-schema: embedded # Database schema initialization mode.
#      schema: classpath:org/quartz/impl/jdbcjobstore/tables_@@platform@@.sql # Path to the SQL file to use to initialize the database schema.
#    quartz
#      job-store-type: memory # Quartz job store type.
#      # properties.*= # Additional Quartz Scheduler properties.      
myapp:
  dataDir: boxes
  downloadFolder: notingit
  ssh:
    sshIdrsa: G:/cygwin64/home/Administrator/.ssh/id_rsa
    knownHosts: G:/cygwin64/home/Administrator/.ssh/known_hosts
using.spring.schedulerFactory: true
expectit.echo: false
scheduler:
  uptime.cron: 0 0/15 * * * ?
  diskfree.cron: 0 0 0 1/1 * ?
  borg.archive.cron: 0 40 12,18 * * ?
  borg.prune.cron: 0 30 23 * * ?
  mysql.flush.cron: 0 30 12,18 * * ?
only.you: yes