CREATE TABLE reuseable_cron (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  description     VARCHAR(200),
  expression      VARCHAR(200)  NOT NULL
);
 
 CREATE TABLE mail_address (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  description     VARCHAR(200),
  email      VARCHAR(200)  NOT NULL
);

CREATE TABLE cron_and_mail (
  mail_id      INT          NOT NULL,
  cron_id        INT          NOT NULL,
   
  PRIMARY KEY (mail_id, cron_id),
  CONSTRAINT fk_ab_mail     FOREIGN KEY (mail_id)  REFERENCES mail_address (id),
  CONSTRAINT fk_ab_cron       FOREIGN KEY (cron_id)    REFERENCES reuseable_cron   (id)
);