CREATE TABLE job_error
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  message_key VARCHAR(1000),
  message_detail BLOB,
  created_at TIMESTAMP(2),
  CONSTRAINT fk_job_error_server FOREIGN KEY (server_id)  REFERENCES server (id)
);

