CREATE TABLE storage_state
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  root VARChAR(128) NOT NULL,
  used BIGINT,
  available BIGINT,
  created_at TIMESTAMP(2),
  CONSTRAINT fk_storage_state_server FOREIGN KEY (server_id)  REFERENCES server (id)
);

CREATE TABLE server_state
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  mem_free BIGINT,
  mem_used BIGINT,
  average_load INTEGER,
  created_at TIMESTAMP(2),
  CONSTRAINT fk_server_state_server FOREIGN KEY (server_id)  REFERENCES server (id)
);