CREATE TABLE server
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  core_number INTEGER,
  host VARCHAR(200) NOT NULL
);

ALTER TABLE server ADD CONSTRAINT unique_host UNIQUE (host);

CREATE TABLE backup_folder
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  folder VARCHAR(1000) NOT NULL,
  CONSTRAINT fk_backup_folder_server FOREIGN KEY (server_id)  REFERENCES server (id)
);

ALTER TABLE backup_folder ADD CONSTRAINT unique_server_folder UNIQUE (server_id, folder);

CREATE TABLE backup_folder_state
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  backup_folder_id INTEGER NOT NULL,
  how_many INTEGER,
  total_size_in_kb INTEGER,
  created_at TIMESTAMP(2),
  CONSTRAINT fk_backup_folder FOREIGN KEY (backup_folder_id)  REFERENCES backup_folder (id)
);

CREATE TABLE up_time
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  load_one INTEGER,
  load_five INTEGER,
  load_fifteen INTEGER,
  uptime_minutes INTEGER,
  created_at TIMESTAMP(2),
  CONSTRAINT fk_up_time_server FOREIGN KEY (server_id)  REFERENCES server (id)
);

