CREATE TABLE diskfree
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  file_system VARCHAR(200) NOT NULL,
  blocks INTEGER,
  used INTEGER,
  available INTEGER,
  use_percent INTEGER,
  mounted_on VARCHAR(200),
  created_at TIMESTAMP(2),
  CONSTRAINT fk_diskfree_server FOREIGN KEY (server_id)  REFERENCES server (id)
);