CREATE TABLE mysql_dump
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  file_size BIGINT,
  result VARCHAR(20),
  time_cost BIGINT,
  created_at TIMESTAMP(2),
  CONSTRAINT fk_mysqldump_server FOREIGN KEY (server_id)  REFERENCES server (id)
);

CREATE TABLE mysql_flush
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  file_size BIGINT,
  file_number INTEGER,
  result VARCHAR(20),
  time_cost BIGINT,
  created_at TIMESTAMP(2),
  CONSTRAINT fk_mysqlflush_server FOREIGN KEY (server_id)  REFERENCES server (id)
);

