CREATE TABLE borg_download
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  created_at TIMESTAMP(2),
  result VARCHAR(20),
  time_cost BIGINT,
  
  total_files INTEGER,
  download_files INTEGER,
  total_bytes BIGINT,
  download_bytes BIGINT,
  CONSTRAINT fk_borg_download_server FOREIGN KEY (server_id)  REFERENCES server (id)
);
