CREATE TABLE robocopy_description
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  repo VARCHAR(256),
  invoke_cron VARCHAR(128),
  local_backup_cron VARCHAR(128),
  prune_strategy VARCHAR(128),
  compress_command VARCHAR(256),
  expand_command VARCHAR(256),
  created_at TIMESTAMP(2),
  CONSTRAINT fk_robo_description_server FOREIGN KEY (server_id)  REFERENCES server (id),
  CONSTRAINT unique_robo_description_server_id UNIQUE (server_id)
);

CREATE TABLE robocopy_item
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  description_id INTEGER NOT NULL,
  source VARCHAR(256),
  dst_relative VARCHAR(256),
  exclude_files VARCHAR(256) ARRAY DEFAULT ARRAY[],
  exclude_directories VARCHAR(256) ARRAY DEFAULT ARRAY[],
  copy_options VARCHAR(256) ARRAY DEFAULT ARRAY[],
  file_selection_options VARCHAR(256) ARRAY DEFAULT ARRAY[],
  retry_options VARCHAR(256) ARRAY DEFAULT ARRAY[],
  logging_options VARCHAR(256) ARRAY DEFAULT ARRAY[],
  job_options VARCHAR(256) ARRAY DEFAULT ARRAY[],
  created_at TIMESTAMP(2),
  CONSTRAINT fk_robo_item_description FOREIGN KEY (description_id)  REFERENCES robocopy_description (id),
  CONSTRAINT unique_robo_item_src_dst UNIQUE (source, dst_relative)
);