CREATE TABLE server
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  name VARChAR(256) NOT NULL,
  core_number INTEGER,
  host VARCHAR(200) NOT NULL,
  port INTEGER NOT NULL,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(64),
  ssh_key_file VARCHAR(256),
  server_state_cron VARCHAR(256),
  storage_state_cron VARCHAR(256),
  server_role VARCHAR(32) DEFAULT 'GET',
  os VARCHAR(64),
  created_at TIMESTAMP(2),
  CONSTRAINT unique_server_host UNIQUE (host)
);


CREATE TABLE server_grp
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  ename VARCHAR(256) NOT NULL,
  msgkey VARCHAR(256),
  created_at TIMESTAMP(2),
  CONSTRAINT unique_servergrp_ename UNIQUE (ename)
);

CREATE TABLE servergrp_and_server (
  server_id INT  NOT NULL,
  grp_id    INT  NOT NULL,
  PRIMARY KEY (server_id, grp_id),
  CONSTRAINT fk_sgs_server     FOREIGN KEY (server_id)  REFERENCES server (id),
  CONSTRAINT fk_sgs_grp       FOREIGN KEY (grp_id)    REFERENCES server_grp   (id)
);


CREATE TABLE reuseable_cron (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  description     VARCHAR(200),
  expression      VARCHAR(200)  NOT NULL,
  created_at TIMESTAMP(2),
  CONSTRAINT unique_rc_expression UNIQUE (expression)
);

 CREATE TABLE user_account (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  name  VARCHAR(200)  NOT NULL,
  mobile  VARCHAR(64)  NOT NULL,
  email      VARCHAR(200)  NOT NULL,
  description     VARCHAR(200),
  created_at TIMESTAMP(2),
  CONSTRAINT unique_ua_email UNIQUE (email),
  CONSTRAINT unique_ua_name UNIQUE (name),
  CONSTRAINT unique_ua_mobile UNIQUE (mobile)
);

CREATE TABLE user_grp
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  ename VARCHAR(256),
  msgkey VARCHAR(256),
  created_at TIMESTAMP(2),
  CONSTRAINT unique_usergrp_ename UNIQUE (ename)
);

CREATE TABLE usergrp_and_user (
  user_id INT  NOT NULL,
  grp_id    INT  NOT NULL,
  PRIMARY KEY (user_id, grp_id),
  CONSTRAINT fk_ugu_user     FOREIGN KEY (user_id)  REFERENCES user_account (id),
  CONSTRAINT fk_ugu_grp       FOREIGN KEY (grp_id)    REFERENCES user_grp   (id)
);

CREATE TABLE big_ob
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  name VARChAR(256) NOT NULL,
  description VARCHAR(256),
  content BLOB,
  created_at TIMESTAMP(2),
  CONSTRAINT unique_big_ob_name UNIQUE (name)
);


CREATE TABLE job_log
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  job_class VARCHAR(128),
  ctx VARCHAR(256),
  exp BLOB,
  created_at TIMESTAMP(2)
);

CREATE TABLE play_back
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  source_server_id INTEGER NOT NULL,
  target_server_id INTEGER NOT NULL,
  play_what VARCHAR(64) NOT NULL,
  pairs VARCHAR(256) ARRAY DEFAULT ARRAY[],
  created_at TIMESTAMP(2),
  CONSTRAINT unique_play_back UNIQUE (source_server_id, target_server_id, play_what)
);

CREATE TABLE key_value
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  item_key VARCHAR(256) NOT NULL,
  item_value VARCHAR(256) NOT NULL,
  created_at TIMESTAMP(2),
  CONSTRAINT unique_key_value_key UNIQUE (item_key)
);

CREATE INDEX job_log_created_at_idx ON job_log(created_at);
