CREATE TABLE key_key_value
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  group_key VARCHAR(64) NOT NULL,
  item_key VARCHAR(64) NOT NULL,
  item_value VARCHAR(256) NOT NULL,
  created_at TIMESTAMP(2),
  CONSTRAINT unique_key_key_value UNIQUE (group_key, item_key, item_value)
);
