CREATE TABLE software
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  name VARChAR(256) NOT NULL,
  version VARChAR(256) NOT NULL,
  target_env VARCHAR(256) NOT NULL,
  website VARCHAR(256),
  dlurl VARCHAR(256),
  installer VARCHAR(256),
  created_at TIMESTAMP(2),
  CONSTRAINT unique_sf_name_version UNIQUE (name, version)
);
