CREATE TABLE software_installation
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  server_id INTEGER NOT NULL,
  software_id INTEGER NOT NULL,
  settings VARCHAR(256) ARRAY DEFAULT ARRAY[],
  created_at TIMESTAMP(2),
  CONSTRAINT unique_si_server_sf_id UNIQUE (server_id, software_id)
);
