CREATE TABLE mail_server_grp
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  mail_address_id INTEGER NOT NULL,
  server_grp_id INTEGER NOT NULL,
  cron_expression VARChAR(256),
  created_at TIMESTAMP(2),
  CONSTRAINT fk_mail_servergrp_grp_id FOREIGN KEY (server_grp_id)  REFERENCES server_grp (id),
  CONSTRAINT fk_mail_servergrp_mail_id FOREIGN KEY (mail_address_id)  REFERENCES mail_address (id)
);

