CREATE TABLE db_pair
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  get_server_id INTEGER,
  set_server_id INTEGER,
  created_at TIMESTAMP(2),
  CONSTRAINT unique_db_pair UNIQUE (get_server_id, set_server_id)
);

CREATE TABLE dir_pair
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  get_server_id INTEGER,
  set_server_id INTEGER,
  new_dir VARCHAR(256),
  created_at TIMESTAMP(2),
  CONSTRAINT unique_dir_pair UNIQUE (set_server_id, new_dir)
);

